# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: muvtuber/chatbot/chatgpt_chatbot/v1/chatgpt_chatbot.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n9muvtuber/chatbot/chatgpt_chatbot/v1/chatgpt_chatbot.proto\x12#muvtuber.chatbot.chatgpt_chatbot.v1\"]\n\x11NewSessionRequest\x12!\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\tR\x0b\x61\x63\x63\x65ssToken\x12%\n\x0einitial_prompt\x18\x02 \x01(\tR\rinitialPrompt\"^\n\x12NewSessionResponse\x12\x1d\n\nsession_id\x18\x01 \x01(\tR\tsessionId\x12)\n\x10initial_response\x18\x02 \x01(\tR\x0finitialResponse\"5\n\x14\x44\x65leteSessionRequest\x12\x1d\n\nsession_id\x18\x01 \x01(\tR\tsessionId\"6\n\x15\x44\x65leteSessionResponse\x12\x1d\n\nsession_id\x18\x01 \x01(\tR\tsessionId\"D\n\x0b\x43hatRequest\x12\x1d\n\nsession_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n\x06prompt\x18\x02 \x01(\tR\x06prompt\"*\n\x0c\x43hatResponse\x12\x1a\n\x08response\x18\x02 \x01(\tR\x08response2\x85\x03\n\x0e\x43hatGPTService\x12}\n\nNewSession\x12\x36.muvtuber.chatbot.chatgpt_chatbot.v1.NewSessionRequest\x1a\x37.muvtuber.chatbot.chatgpt_chatbot.v1.NewSessionResponse\x12k\n\x04\x43hat\x12\x30.muvtuber.chatbot.chatgpt_chatbot.v1.ChatRequest\x1a\x31.muvtuber.chatbot.chatgpt_chatbot.v1.ChatResponse\x12\x86\x01\n\rDeleteSession\x12\x39.muvtuber.chatbot.chatgpt_chatbot.v1.DeleteSessionRequest\x1a:.muvtuber.chatbot.chatgpt_chatbot.v1.DeleteSessionResponseB\xb3\x02\n\'com.muvtuber.chatbot.chatgpt_chatbot.v1B\x13\x43hatgptChatbotProtoP\x01ZHmuvtuberdriver/gen/muvtuber/chatbot/chatgpt_chatbot/v1;chatgpt_chatbotv1\xa2\x02\x03MCC\xaa\x02\"Muvtuber.Chatbot.ChatgptChatbot.V1\xca\x02\"Muvtuber\\Chatbot\\ChatgptChatbot\\V1\xe2\x02.Muvtuber\\Chatbot\\ChatgptChatbot\\V1\\GPBMetadata\xea\x02%Muvtuber::Chatbot::ChatgptChatbot::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'muvtuber.chatbot.chatgpt_chatbot.v1.chatgpt_chatbot_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\'com.muvtuber.chatbot.chatgpt_chatbot.v1B\023ChatgptChatbotProtoP\001ZHmuvtuberdriver/gen/muvtuber/chatbot/chatgpt_chatbot/v1;chatgpt_chatbotv1\242\002\003MCC\252\002\"Muvtuber.Chatbot.ChatgptChatbot.V1\312\002\"Muvtuber\\Chatbot\\ChatgptChatbot\\V1\342\002.Muvtuber\\Chatbot\\ChatgptChatbot\\V1\\GPBMetadata\352\002%Muvtuber::Chatbot::ChatgptChatbot::V1'
  _globals['_NEWSESSIONREQUEST']._serialized_start=98
  _globals['_NEWSESSIONREQUEST']._serialized_end=191
  _globals['_NEWSESSIONRESPONSE']._serialized_start=193
  _globals['_NEWSESSIONRESPONSE']._serialized_end=287
  _globals['_DELETESESSIONREQUEST']._serialized_start=289
  _globals['_DELETESESSIONREQUEST']._serialized_end=342
  _globals['_DELETESESSIONRESPONSE']._serialized_start=344
  _globals['_DELETESESSIONRESPONSE']._serialized_end=398
  _globals['_CHATREQUEST']._serialized_start=400
  _globals['_CHATREQUEST']._serialized_end=468
  _globals['_CHATRESPONSE']._serialized_start=470
  _globals['_CHATRESPONSE']._serialized_end=512
  _globals['_CHATGPTSERVICE']._serialized_start=515
  _globals['_CHATGPTSERVICE']._serialized_end=904
# @@protoc_insertion_point(module_scope)
