# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from muvtuber.chatbot.chatgpt_chatbot.v1 import chatgpt_chatbot_pb2 as muvtuber_dot_chatbot_dot_chatgpt__chatbot_dot_v1_dot_chatgpt__chatbot__pb2


class ChatGPTServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.NewSession = channel.unary_unary(
                '/muvtuber.chatbot.chatgpt_chatbot.v1.ChatGPTService/NewSession',
                request_serializer=muvtuber_dot_chatbot_dot_chatgpt__chatbot_dot_v1_dot_chatgpt__chatbot__pb2.NewSessionRequest.SerializeToString,
                response_deserializer=muvtuber_dot_chatbot_dot_chatgpt__chatbot_dot_v1_dot_chatgpt__chatbot__pb2.NewSessionResponse.FromString,
                )
        self.Chat = channel.unary_unary(
                '/muvtuber.chatbot.chatgpt_chatbot.v1.ChatGPTService/Chat',
                request_serializer=muvtuber_dot_chatbot_dot_chatgpt__chatbot_dot_v1_dot_chatgpt__chatbot__pb2.ChatRequest.SerializeToString,
                response_deserializer=muvtuber_dot_chatbot_dot_chatgpt__chatbot_dot_v1_dot_chatgpt__chatbot__pb2.ChatResponse.FromString,
                )
        self.DeleteSession = channel.unary_unary(
                '/muvtuber.chatbot.chatgpt_chatbot.v1.ChatGPTService/DeleteSession',
                request_serializer=muvtuber_dot_chatbot_dot_chatgpt__chatbot_dot_v1_dot_chatgpt__chatbot__pb2.DeleteSessionRequest.SerializeToString,
                response_deserializer=muvtuber_dot_chatbot_dot_chatgpt__chatbot_dot_v1_dot_chatgpt__chatbot__pb2.DeleteSessionResponse.FromString,
                )


class ChatGPTServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def NewSession(self, request, context):
        """NewSession creates a new session with ChatGPT.
        Input: access_token (string) and initial_prompt (string).
        Output: session_id (string).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Chat(self, request, context):
        """Chat sends a prompt to ChatGPT and receives a response.
        Input: session_id (string) and prompt (string).
        Output: response (string).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSession(self, request, context):
        """DeleteSession deletes a session with ChatGPT.
        Input: session_id (string).
        Output: session_id (string).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChatGPTServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'NewSession': grpc.unary_unary_rpc_method_handler(
                    servicer.NewSession,
                    request_deserializer=muvtuber_dot_chatbot_dot_chatgpt__chatbot_dot_v1_dot_chatgpt__chatbot__pb2.NewSessionRequest.FromString,
                    response_serializer=muvtuber_dot_chatbot_dot_chatgpt__chatbot_dot_v1_dot_chatgpt__chatbot__pb2.NewSessionResponse.SerializeToString,
            ),
            'Chat': grpc.unary_unary_rpc_method_handler(
                    servicer.Chat,
                    request_deserializer=muvtuber_dot_chatbot_dot_chatgpt__chatbot_dot_v1_dot_chatgpt__chatbot__pb2.ChatRequest.FromString,
                    response_serializer=muvtuber_dot_chatbot_dot_chatgpt__chatbot_dot_v1_dot_chatgpt__chatbot__pb2.ChatResponse.SerializeToString,
            ),
            'DeleteSession': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSession,
                    request_deserializer=muvtuber_dot_chatbot_dot_chatgpt__chatbot_dot_v1_dot_chatgpt__chatbot__pb2.DeleteSessionRequest.FromString,
                    response_serializer=muvtuber_dot_chatbot_dot_chatgpt__chatbot_dot_v1_dot_chatgpt__chatbot__pb2.DeleteSessionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'muvtuber.chatbot.chatgpt_chatbot.v1.ChatGPTService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ChatGPTService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def NewSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/muvtuber.chatbot.chatgpt_chatbot.v1.ChatGPTService/NewSession',
            muvtuber_dot_chatbot_dot_chatgpt__chatbot_dot_v1_dot_chatgpt__chatbot__pb2.NewSessionRequest.SerializeToString,
            muvtuber_dot_chatbot_dot_chatgpt__chatbot_dot_v1_dot_chatgpt__chatbot__pb2.NewSessionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Chat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/muvtuber.chatbot.chatgpt_chatbot.v1.ChatGPTService/Chat',
            muvtuber_dot_chatbot_dot_chatgpt__chatbot_dot_v1_dot_chatgpt__chatbot__pb2.ChatRequest.SerializeToString,
            muvtuber_dot_chatbot_dot_chatgpt__chatbot_dot_v1_dot_chatgpt__chatbot__pb2.ChatResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/muvtuber.chatbot.chatgpt_chatbot.v1.ChatGPTService/DeleteSession',
            muvtuber_dot_chatbot_dot_chatgpt__chatbot_dot_v1_dot_chatgpt__chatbot__pb2.DeleteSessionRequest.SerializeToString,
            muvtuber_dot_chatbot_dot_chatgpt__chatbot_dot_v1_dot_chatgpt__chatbot__pb2.DeleteSessionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
