# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: muvtuber/chatbot/musharing_chatbot/v1/musharing_chatbot.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n=muvtuber/chatbot/musharing_chatbot/v1/musharing_chatbot.proto\x12%muvtuber.chatbot.musharing_chatbot.v1\"%\n\x0b\x43hatRequest\x12\x16\n\x06prompt\x18\x01 \x01(\tR\x06prompt\"*\n\x0c\x43hatResponse\x12\x1a\n\x08response\x18\x01 \x01(\tR\x08response2\x81\x01\n\x0e\x43hatbotService\x12o\n\x04\x43hat\x12\x32.muvtuber.chatbot.musharing_chatbot.v1.ChatRequest\x1a\x33.muvtuber.chatbot.musharing_chatbot.v1.ChatResponseB\xc3\x02\n)com.muvtuber.chatbot.musharing_chatbot.v1B\x15MusharingChatbotProtoP\x01ZLmuvtuberdriver/gen/muvtuber/chatbot/musharing_chatbot/v1;musharing_chatbotv1\xa2\x02\x03MCM\xaa\x02$Muvtuber.Chatbot.MusharingChatbot.V1\xca\x02$Muvtuber\\Chatbot\\MusharingChatbot\\V1\xe2\x02\x30Muvtuber\\Chatbot\\MusharingChatbot\\V1\\GPBMetadata\xea\x02\'Muvtuber::Chatbot::MusharingChatbot::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'muvtuber.chatbot.musharing_chatbot.v1.musharing_chatbot_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n)com.muvtuber.chatbot.musharing_chatbot.v1B\025MusharingChatbotProtoP\001ZLmuvtuberdriver/gen/muvtuber/chatbot/musharing_chatbot/v1;musharing_chatbotv1\242\002\003MCM\252\002$Muvtuber.Chatbot.MusharingChatbot.V1\312\002$Muvtuber\\Chatbot\\MusharingChatbot\\V1\342\0020Muvtuber\\Chatbot\\MusharingChatbot\\V1\\GPBMetadata\352\002\'Muvtuber::Chatbot::MusharingChatbot::V1'
  _globals['_CHATREQUEST']._serialized_start=104
  _globals['_CHATREQUEST']._serialized_end=141
  _globals['_CHATRESPONSE']._serialized_start=143
  _globals['_CHATRESPONSE']._serialized_end=185
  _globals['_CHATBOTSERVICE']._serialized_start=188
  _globals['_CHATBOTSERVICE']._serialized_end=317
# @@protoc_insertion_point(module_scope)
